<?php
declare( strict_types=1 );

/**
 * Custom escaping and sanitization functions.
 *
 * Must be added to the `phpcs.xml` and PHPStan of the consuming project.
 *
 * @see AGENTS.md
 *
 * @version 1.7.0
 */

/**
 * Lightweight enforcing of string value without the
 * overhead of escaping functions like `esc_attr`.
 *
 * For use with outputting CSS modules class names.
 *
 * @notice This does not escape. Use `esc_attr`, `esc_url`, or `esc_html`
 *         for any value which reaches a non "class" HTML attribute or
 *         is not generated by the build.
 *
 * @link phpcs.xml
 */
function es( BackedEnum|float|Stringable|int|string|null $value ): string {
	if ( $value instanceof BackedEnum ) {
		return (string) $value->value;
	}
	return (string) $value;
}

/**
 * Sanitize a submitted value, typically from $_POST.
 *
 * Simplifies the typical unslash then sanitize process.
 *
 * Calls `trim` and `sanitize_text_field` on the value so no need
 * to call them separately.
 *
 * @phpstan-return ($value is null? null : string)
 */
function sn( float|int|string|null $value ): ?string {
	if ( null === $value ) {
		return null;
	}
	if ( \is_string( $value ) ) {
		$value = \trim( sanitize_text_field( wp_unslash( $value ) ) );
	}
	return (string) $value;
}
